name: frontend_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  record: ^5.1.2
  audioplayers: ^5.2.1
  permission_handler: ^11.3.1
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.4
  path: ^1.9.0
  vector_math: ^2.1.4
  vm_service: 14.3.1
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true